name: Build and Push ChatTTS-Enhanced Docker Images

on:
  workflow_dispatch:
  schedule:
    # 每月3号凌晨0点运行
    - cron: '0 0 3 * *'
  push:
    tags:
      - 'v*'

env:
  CODING_DOCKER_REGISTRY: ${{ secrets.CODING_DOCKER_REGISTRY }}
  CODING_DOCKER_IMAGE: ${{ secrets.CODING_DOCKER_REGISTRY }}/chattts-enhanced

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: CODING
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 获取最新tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "latest")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"
          
      - name: 检出最新tag
        run: |
          if [ "$LATEST_TAG" != "latest" ]; then
            git checkout $LATEST_TAG
            echo "已检出版本: $LATEST_TAG"
          else
            echo "未找到tag，使用最新主分支"
          fi

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录腾讯Coding容器镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CODING_DOCKER_REGISTRY }}
          username: ${{ secrets.CODING_DOCKER_USER }}
          password: ${{ secrets.CODING_DOCKER_TOKEN }}
            
      - name: 构建并推送ChatTTS-Enhanced Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.CODING_DOCKER_IMAGE }}:latest
            ${{ env.CODING_DOCKER_IMAGE }}:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: 构建状态通知
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ ChatTTS-Enhanced Docker镜像构建成功!"
            echo "镜像版本: ${{ env.LATEST_TAG }}"
            echo "镜像标签: ${{ env.CODING_DOCKER_IMAGE }}:latest, ${{ env.CODING_DOCKER_IMAGE }}:${{ env.LATEST_TAG }}"
            echo "镜像仓库: ${{ env.CODING_DOCKER_REGISTRY }}"
          else
            echo "❌ ChatTTS-Enhanced Docker镜像构建失败!"
            exit 1
          fi 